name = "VSFlow"
uuid = "4888aff6-796c-4664-9fba-d638b346e305"
authors = ["Denis Dumoulin"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
